name: t2v
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip=23.0.1
  - pytorch=2.0.0
  - pip:
    - accelerate==0.18.0
    - diffusers==0.16.1
    - transformers==4.29.2
    - opencv-python==4.7.0.72
    - streamlit==1.20.0
